version: 2

builds:
  - id: glyphoxa
    main: ./cmd/glyphoxa
    binary: glyphoxa
    env:
      - CGO_ENABLED=1
      - CGO_CFLAGS=-I/tmp/whisper/include
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    overrides:
      - goos: linux
        goarch: amd64
        env:
          - CC=x86_64-linux-gnu-gcc
          - CXX=x86_64-linux-gnu-g++
          - CGO_LDFLAGS=-L/tmp/whisper/amd64/lib
      - goos: linux
        goarch: arm64
        env:
          - CC=aarch64-linux-gnu-gcc
          - CXX=aarch64-linux-gnu-g++
          - CGO_LDFLAGS=-L/tmp/whisper/arm64/lib -lm
          - PKG_CONFIG_LIBDIR=/tmp/opus/arm64/lib/pkgconfig
    ldflags:
      - -s -w -linkmode external -extldflags "-static"

archives:
  - id: default
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  github:
    owner: MrWong99
    name: glyphoxa
  draft: false
  prerelease: auto
  name_template: "{{ .Version }}"
  header: |
    # Release {{ .Version }}
  footer: |
    # Glyphoxa Docker image
    docker pull ghcr.io/mrwong99/glyphoxa:v{{ .Version }}

    Release Date: {{ .Date }}
