name: Bug Report
description: Something isn't working as expected.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug!
        A clear report helps us fix it faster.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug.
      placeholder: "What happened? What did you expect to happen instead?"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Configure NPC with engine: s2s
        2. Start voice session
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened.
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Glyphoxa Version
      description: Commit SHA or version tag you are running.
      placeholder: "e.g. v0.1.0 or abc1234"
    validations:
      required: true

  - type: input
    id: go-version
    attributes:
      label: Go Version
      description: Output of `go version`.
      placeholder: "e.g. go1.26.0 linux/amd64"
    validations:
      required: false

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Linux
        - macOS
        - Windows
        - Other
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of Glyphoxa is affected?
      options:
        - Audio Platform (Discord/WebRTC)
        - STT Provider
        - LLM Provider
        - TTS Provider
        - S2S Provider
        - Agent/Orchestrator
        - Memory System
        - MCP Tools
        - Configuration
        - Other
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: Paste any relevant logs, error messages, or stack traces.
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Anything else — screenshots, config snippets, provider details, etc.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched the existing issues to make sure this is not a duplicate.
          required: true
        - label: I have run `make check` and confirmed the issue is not caused by my local setup.
          required: false
