name: Feature Request
description: Suggest a new feature or enhancement.
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Got an idea that could make Glyphoxa better? We'd love to hear it.
        The more specific the better — API sketches, config examples, and
        architecture ideas are all welcome.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem?
      placeholder: "I'm always frustrated when ..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative approaches?

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which part of Glyphoxa does this relate to?
      options:
        - Audio Platform (Discord/WebRTC)
        - STT/TTS Providers
        - LLM/S2S Providers
        - Agent/NPC System
        - Memory/Knowledge Graph
        - MCP Tools
        - Entity Management
        - Sentence Cascade
        - Configuration
        - Documentation
        - Build / Tooling
        - Other
    validations:
      required: true

  - type: dropdown
    id: willing
    attributes:
      label: Would you be willing to contribute this?
      options:
        - "Yes, I'd like to submit a PR"
        - "Maybe, with some guidance"
        - "No, just suggesting"
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, mockups, references, or examples.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched the existing issues to make sure this has not already been requested.
          required: true
