//go:build voice_e2e

// Package session contains end-to-end integration tests for the full voice
// pipeline: Energy VAD → Whisper STT (native CGO) → Address Detection →
// NPC Agent → Cascade Engine (mock LLM + mock TTS) → Priority Mixer →
// Loopback Output.
//
// Test audio is generated by ElevenLabs TTS. The LLM and TTS stages use
// mocks to keep the test deterministic. Energy-based VAD is used instead of
// Silero due to an ONNX Runtime 1.24 compatibility issue (documented in
// TestVoiceE2E_SileroVAD).
//
// NOTE: Whisper.cpp Go bindings have an inherent data race in
// registerProgressCallback (upstream issue). These tests must NOT run with
// -race when using parallel Whisper sessions. The full-pipeline tests
// (NPC addressing, speaker switching, etc.) run sequentially within each
// test function.
//
// Prerequisites:
//   - whisper.cpp: make whisper-libs && export C_INCLUDE_PATH=/tmp/whisper-install/include LIBRARY_PATH=/tmp/whisper-install/lib
//   - Whisper model: ggml-base.en.bin at /tmp/whisper-models/ggml-base.en.bin
//   - Test audio: testdata/audio/*.pcm (generated by ElevenLabs TTS)
//
// Run: go test -tags voice_e2e -count=1 -run TestVoiceE2E -v -timeout 300s ./internal/session/
package session

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/MrWong99/glyphoxa/internal/agent"
	"github.com/MrWong99/glyphoxa/internal/agent/orchestrator"
	"github.com/MrWong99/glyphoxa/internal/engine/cascade"
	"github.com/MrWong99/glyphoxa/internal/hotctx"
	"github.com/MrWong99/glyphoxa/pkg/audio"
	"github.com/MrWong99/glyphoxa/pkg/audio/loopback"
	"github.com/MrWong99/glyphoxa/pkg/audio/mixer"
	"github.com/MrWong99/glyphoxa/pkg/memory"
	"github.com/MrWong99/glyphoxa/pkg/provider/llm"
	llmmock "github.com/MrWong99/glyphoxa/pkg/provider/llm/mock"
	"github.com/MrWong99/glyphoxa/pkg/provider/stt"
	sttwhisper "github.com/MrWong99/glyphoxa/pkg/provider/stt/whisper"
	"github.com/MrWong99/glyphoxa/pkg/provider/tts"
	ttsmock "github.com/MrWong99/glyphoxa/pkg/provider/tts/mock"
	"github.com/MrWong99/glyphoxa/pkg/provider/vad"
	energyvad "github.com/MrWong99/glyphoxa/pkg/provider/vad/energy"
	silerovad "github.com/MrWong99/glyphoxa/pkg/provider/vad/silero"
)

const (
	whisperModelPath = "/tmp/whisper-models/ggml-base.en.bin"
	sttSampleRate    = 16000
	vadFrameSizeMs   = 30
	pipelineTimeout  = 60 * time.Second
)

// ─── Mock memory stores ─────────────────────────────────────────────────────

type noopSessionStore struct{}

func (noopSessionStore) WriteEntry(context.Context, string, memory.TranscriptEntry) error { return nil }
func (noopSessionStore) GetRecent(context.Context, string, time.Duration) ([]memory.TranscriptEntry, error) {
	return nil, nil
}
func (noopSessionStore) Search(context.Context, string, memory.SearchOpts) ([]memory.TranscriptEntry, error) {
	return nil, nil
}
func (noopSessionStore) EntryCount(context.Context, string) (int, error) { return 0, nil }
func (noopSessionStore) ListSessions(context.Context, int) ([]memory.SessionInfo, error) {
	return nil, nil
}
func (noopSessionStore) StartSession(context.Context, string) error { return nil }
func (noopSessionStore) EndSession(context.Context, string) error   { return nil }

type noopKnowledgeGraph struct{}

func (noopKnowledgeGraph) AddEntity(context.Context, memory.Entity) error { return nil }
func (noopKnowledgeGraph) GetEntity(context.Context, string) (*memory.Entity, error) {
	return nil, nil
}
func (noopKnowledgeGraph) UpdateEntity(context.Context, string, map[string]any) error { return nil }
func (noopKnowledgeGraph) DeleteEntity(context.Context, string) error                 { return nil }
func (noopKnowledgeGraph) FindEntities(context.Context, memory.EntityFilter) ([]memory.Entity, error) {
	return nil, nil
}
func (noopKnowledgeGraph) AddRelationship(context.Context, memory.Relationship) error { return nil }
func (noopKnowledgeGraph) GetRelationships(context.Context, string, ...memory.RelQueryOpt) ([]memory.Relationship, error) {
	return nil, nil
}
func (noopKnowledgeGraph) DeleteRelationship(context.Context, string, string, string) error {
	return nil
}
func (noopKnowledgeGraph) Neighbors(context.Context, string, int, ...memory.TraversalOpt) ([]memory.Entity, error) {
	return nil, nil
}
func (noopKnowledgeGraph) FindPath(context.Context, string, string, int) ([]memory.Entity, error) {
	return nil, nil
}
func (noopKnowledgeGraph) VisibleSubgraph(context.Context, string) ([]memory.Entity, []memory.Relationship, error) {
	return nil, nil, nil
}
func (noopKnowledgeGraph) IdentitySnapshot(context.Context, string) (*memory.NPCIdentity, error) {
	return &memory.NPCIdentity{}, nil
}

// ─── Test harness ────────────────────────────────────────────────────────────

type e2eResult struct {
	RoutedTo         string
	TranscribedText  string
	VADLatency       time.Duration
	STTLatency       time.Duration
	TotalLatency     time.Duration
	OutputFrameCount int
}

type npcConfig struct {
	ID, Name, Personality, VoiceID, LLMResponse string
}

type e2eHarness struct {
	t           *testing.T
	vadEngine   vad.Engine
	sttProvider *sttwhisper.NativeProvider
	mx          *mixer.PriorityMixer
	orch        *orchestrator.Orchestrator
	conn        *loopback.Connection
}

func newE2EHarness(t *testing.T, npcs []npcConfig) *e2eHarness {
	t.Helper()

	vadEng := energyvad.New(
		energyvad.WithMinSpeechFrames(2),
		energyvad.WithMinSilenceFrames(12),
		energyvad.WithMinSpeechDurationFrames(5),
	)

	modelPath := whisperModelPath
	if p := os.Getenv("WHISPER_MODEL_PATH"); p != "" {
		modelPath = p
	}
	sttP, err := sttwhisper.NewNative(modelPath,
		sttwhisper.WithNativeLanguage("en"),
		sttwhisper.WithNativeSampleRate(sttSampleRate),
		sttwhisper.WithNativeSilenceThresholdMs(300),
		sttwhisper.WithNativeMaxBufferDurationMs(10000),
	)
	if err != nil {
		t.Fatalf("create whisper STT: %v", err)
	}
	t.Cleanup(func() { sttP.Close() })

	assembler := hotctx.NewAssembler(noopSessionStore{}, noopKnowledgeGraph{},
		hotctx.WithAssemblyTimeout(5*time.Second))

	conn := loopback.New(nil)
	t.Cleanup(func() { conn.Disconnect() })

	mx := mixer.New(func(frame audio.AudioFrame) {
		select {
		case conn.OutputStream() <- frame:
		default:
		}
	}, mixer.WithGap(100*time.Millisecond))
	t.Cleanup(func() { mx.Close() })

	var agentSlice []agent.NPCAgent
	for _, npc := range npcs {
		mockLLM := &llmmock.Provider{
			StreamChunks: []llm.Chunk{{Text: npc.LLMResponse, FinishReason: "stop"}},
		}
		mockTTS := &ttsmock.Provider{
			SynthesizeChunks: [][]byte{makeSilentPCM(sttSampleRate, 1, 500)},
		}
		voice := tts.VoiceProfile{ID: npc.VoiceID, Name: npc.Name + " Voice"}
		eng := cascade.New(mockLLM, mockLLM, mockTTS, voice, cascade.WithTTSFormat(sttSampleRate, 1))
		t.Cleanup(func() { eng.Close() })

		ag, err := agent.NewAgent(agent.AgentConfig{
			ID: npc.ID, Identity: agent.NPCIdentity{Name: npc.Name, Personality: npc.Personality},
			Engine: eng, Assembler: assembler, Mixer: mx, SessionID: "e2e-test-session",
		})
		if err != nil {
			t.Fatalf("create agent %s: %v", npc.Name, err)
		}
		agentSlice = append(agentSlice, ag)
	}

	return &e2eHarness{
		t: t, vadEngine: vadEng, sttProvider: sttP, mx: mx,
		orch: orchestrator.New(agentSlice, orchestrator.WithMixer(mx)),
		conn: conn,
	}
}

func (h *e2eHarness) runPipeline(ctx context.Context, pcmData []byte, speakerID string) (*e2eResult, error) {
	h.t.Helper()
	result := &e2eResult{}
	startTime := time.Now()

	vadSess, err := h.vadEngine.NewSession(vad.Config{
		SampleRate: sttSampleRate, FrameSizeMs: vadFrameSizeMs,
		SpeechThreshold: 0.5, SilenceThreshold: 0.35,
	})
	if err != nil {
		return nil, fmt.Errorf("create VAD session: %w", err)
	}
	defer vadSess.Close()

	frameSizeBytes := sttSampleRate * vadFrameSizeMs / 1000 * 2
	const preBufferFrames = 3

	// Phase 1: VAD — buffer speech frames.
	var speechBuf []byte
	var vadSpeechStarted bool
	var speechEndTime time.Time
	preBuffer := make([][]byte, 0, preBufferFrames)

	for offset := 0; offset+frameSizeBytes <= len(pcmData); offset += frameSizeBytes {
		frame := make([]byte, frameSizeBytes)
		copy(frame, pcmData[offset:offset+frameSizeBytes])

		vadEvent, err := vadSess.ProcessFrame(frame)
		if err != nil {
			return nil, fmt.Errorf("VAD: %w", err)
		}

		switch vadEvent.Type {
		case vad.VADSpeechStart:
			if !vadSpeechStarted {
				result.VADLatency = time.Since(startTime)
				vadSpeechStarted = true
				for _, pf := range preBuffer {
					speechBuf = append(speechBuf, pf...)
				}
			}
			speechBuf = append(speechBuf, frame...)
		case vad.VADSpeechContinue:
			speechBuf = append(speechBuf, frame...)
		case vad.VADSpeechEnd:
			speechEndTime = time.Now()
			speechBuf = append(speechBuf, frame...)
		case vad.VADSilence:
			if vadSpeechStarted {
				speechBuf = append(speechBuf, frame...)
			} else {
				if len(preBuffer) >= preBufferFrames {
					preBuffer = preBuffer[1:]
				}
				preBuffer = append(preBuffer, frame)
			}
		}
	}

	if !vadSpeechStarted {
		h.t.Log("VAD did not detect speech, sending all audio to STT")
		speechBuf = pcmData
	}
	if vadSpeechStarted && speechEndTime.IsZero() {
		speechEndTime = time.Now()
	}

	// Phase 2: STT — send speech buffer to Whisper.
	sttSess, err := h.sttProvider.StartStream(ctx, stt.StreamConfig{
		SampleRate: sttSampleRate, Channels: 1,
	})
	if err != nil {
		return nil, fmt.Errorf("create STT session: %w", err)
	}

	chunkSize := sttSampleRate * 2 / 10 // 100ms chunks
	for offset := 0; offset < len(speechBuf); offset += chunkSize {
		end := min(offset+chunkSize, len(speechBuf))
		_ = sttSess.SendAudio(speechBuf[offset:end])
	}
	// Trailing silence to trigger STT flush.
	silence := makeSilentPCM(sttSampleRate, 1, 1500)
	for offset := 0; offset < len(silence); offset += chunkSize {
		end := min(offset+chunkSize, len(silence))
		_ = sttSess.SendAudio(silence[offset:end])
	}

	var transcript stt.Transcript
	select {
	case t, ok := <-sttSess.Finals():
		if ok {
			transcript = t
		}
	case <-time.After(15 * time.Second):
		sttSess.Close()
		select {
		case t, ok := <-sttSess.Finals():
			if ok {
				transcript = t
			}
		case <-time.After(5 * time.Second):
			return nil, fmt.Errorf("STT finals timeout")
		}
	}
	sttSess.Close()

	if !speechEndTime.IsZero() {
		result.STTLatency = time.Since(speechEndTime)
	}
	result.TranscribedText = transcript.Text
	h.t.Logf("STT: %q (%.1fs audio)", transcript.Text, float64(len(speechBuf))/float64(sttSampleRate*2))

	if transcript.Text == "" {
		return result, fmt.Errorf("STT produced empty transcript")
	}

	targetAgent, err := h.orch.Route(ctx, speakerID, transcript)
	if err != nil {
		return result, fmt.Errorf("orchestrator route: %w", err)
	}
	result.RoutedTo = targetAgent.ID()

	if err := targetAgent.HandleUtterance(ctx, speakerID, transcript); err != nil {
		return result, fmt.Errorf("handle utterance: %w", err)
	}
	if h.conn.WaitForOutput(1, 5*time.Second) {
		result.OutputFrameCount = h.conn.CapturedOutputCount()
	}
	result.TotalLatency = time.Since(startTime)
	return result, nil
}

func loadPCM(t *testing.T, name string) []byte {
	t.Helper()
	data, err := os.ReadFile(filepath.Join("testdata", "audio", name+".pcm"))
	if err != nil {
		t.Fatalf("load PCM %s: %v", name, err)
	}
	t.Logf("loaded %s: %d bytes (%.1fs)", name, len(data), float64(len(data))/float64(sttSampleRate*2))
	return data
}

func makeSilentPCM(sampleRate, channels, durationMs int) []byte {
	return make([]byte, sampleRate*channels*durationMs/1000*2)
}

func containsCI(s, substr string) bool {
	return strings.Contains(strings.ToLower(s), strings.ToLower(substr))
}

// ─── Tests: NPC Addressing (2 NPCs) ────────────────────────────────────────

func TestVoiceE2E_NPCAddressing(t *testing.T) {
	t.Parallel()
	harness := newE2EHarness(t, []npcConfig{
		{ID: "gandalf", Name: "Gandalf", Personality: "A wise wizard.", VoiceID: "gandalf-v",
			LLMResponse: "The One Ring must be destroyed in Mount Doom."},
		{ID: "elena", Name: "Elena", Personality: "A mysterious elven ranger.", VoiceID: "elena-v",
			LLMResponse: "The quest ahead is perilous."},
	})
	ctx, cancel := context.WithTimeout(context.Background(), pipelineTimeout)
	defer cancel()

	// Gandalf: "Hey Gandalf, tell me about the ring."
	pcmGandalf := loadPCM(t, "address_gandalf")
	r1, err := harness.runPipeline(ctx, pcmGandalf, "player-1")
	if err != nil {
		t.Fatalf("gandalf: %v", err)
	}
	if r1.RoutedTo != "gandalf" {
		t.Errorf("gandalf: routed to %q, want gandalf", r1.RoutedTo)
	}
	if !containsCI(r1.TranscribedText, "gandalf") {
		t.Errorf("gandalf: transcript %q missing name", r1.TranscribedText)
	}
	t.Logf("Gandalf: VAD=%v STT=%v Total=%v output=%d frames",
		r1.VADLatency, r1.STTLatency, r1.TotalLatency, r1.OutputFrameCount)

	// Elena: "Hey Elena, what do you think about this quest?"
	pcmElena := loadPCM(t, "address_elena")
	r2, err := harness.runPipeline(ctx, pcmElena, "player-2")
	if err != nil {
		t.Fatalf("elena: %v", err)
	}
	if r2.RoutedTo != "elena" {
		t.Errorf("elena: routed to %q, want elena", r2.RoutedTo)
	}
	if !containsCI(r2.TranscribedText, "elena") {
		t.Errorf("elena: transcript %q missing name", r2.TranscribedText)
	}
	t.Logf("Elena: VAD=%v STT=%v Total=%v output=%d frames",
		r2.VADLatency, r2.STTLatency, r2.TotalLatency, r2.OutputFrameCount)
}

// ─── Tests: Speaker Switching ───────────────────────────────────────────────

func TestVoiceE2E_SpeakerSwitching(t *testing.T) {
	t.Parallel()
	harness := newE2EHarness(t, []npcConfig{
		{ID: "gandalf", Name: "Gandalf", Personality: "A wise wizard.", VoiceID: "gandalf-v",
			LLMResponse: "Indeed, the ring is dangerous."},
		{ID: "elena", Name: "Elena", Personality: "An elven ranger.", VoiceID: "elena-v",
			LLMResponse: "The forest holds many secrets."},
	})
	ctx, cancel := context.WithTimeout(context.Background(), 2*pipelineTimeout)
	defer cancel()

	r1, err := harness.runPipeline(ctx, loadPCM(t, "address_gandalf"), "player-1")
	if err != nil {
		t.Fatalf("utterance 1: %v", err)
	}
	if r1.RoutedTo != "gandalf" {
		t.Errorf("utterance 1: routed to %q, want gandalf", r1.RoutedTo)
	}

	r2, err := harness.runPipeline(ctx, loadPCM(t, "address_elena"), "player-1")
	if err != nil {
		t.Fatalf("utterance 2: %v", err)
	}
	if r2.RoutedTo != "elena" {
		t.Errorf("utterance 2: routed to %q, want elena", r2.RoutedTo)
	}

	r3, err := harness.runPipeline(ctx, loadPCM(t, "no_name_continuation"), "player-1")
	if err != nil {
		t.Fatalf("utterance 3: %v", err)
	}
	if r3.RoutedTo != "elena" {
		t.Errorf("utterance 3: routed to %q, want elena (last-speaker)", r3.RoutedTo)
	}

	t.Logf("Switching: Gandalf→Elena→Elena(cont). Latencies: %v / %v / %v",
		r1.TotalLatency, r2.TotalLatency, r3.TotalLatency)
}

// ─── Tests: Barge-In ────────────────────────────────────────────────────────

func TestVoiceE2E_BargeIn(t *testing.T) {
	t.Parallel()
	harness := newE2EHarness(t, []npcConfig{
		{ID: "gandalf", Name: "Gandalf", Personality: "A wise wizard.", VoiceID: "gandalf-v",
			LLMResponse: "A long story about the ring and its history through the ages of Middle Earth."},
		{ID: "elena", Name: "Elena", Personality: "Elven ranger.", VoiceID: "elena-v",
			LLMResponse: "Yes."},
	})
	ctx, cancel := context.WithTimeout(context.Background(), 2*pipelineTimeout)
	defer cancel()

	var bargeInMu sync.Mutex
	var bargeInCount int
	harness.mx.OnBargeIn(func(_ string) {
		bargeInMu.Lock()
		bargeInCount++
		bargeInMu.Unlock()
	})

	r1, err := harness.runPipeline(ctx, loadPCM(t, "address_gandalf"), "player-1")
	if err != nil {
		t.Fatalf("utterance 1: %v", err)
	}
	if r1.RoutedTo != "gandalf" {
		t.Errorf("utterance 1: routed to %q, want gandalf", r1.RoutedTo)
	}

	time.Sleep(100 * time.Millisecond)
	harness.mx.BargeIn("player-1")
	time.Sleep(50 * time.Millisecond)

	r2, err := harness.runPipeline(ctx, loadPCM(t, "bargein_gandalf"), "player-1")
	if err != nil {
		t.Fatalf("barge-in: %v", err)
	}
	if r2.RoutedTo != "gandalf" {
		t.Errorf("barge-in: routed to %q, want gandalf", r2.RoutedTo)
	}

	bargeInMu.Lock()
	count := bargeInCount
	bargeInMu.Unlock()
	if count < 1 {
		t.Errorf("expected ≥1 barge-in, got %d", count)
	}
	t.Logf("Barge-in: %d events. Latencies: %v / %v", count, r1.TotalLatency, r2.TotalLatency)
}

// ─── Tests: Latency ─────────────────────────────────────────────────────────

func TestVoiceE2E_Latency(t *testing.T) {
	t.Parallel()
	harness := newE2EHarness(t, []npcConfig{
		{ID: "gandalf", Name: "Gandalf", Personality: "A wizard.", VoiceID: "gandalf-v",
			LLMResponse: "The ring must be destroyed."},
	})
	ctx, cancel := context.WithTimeout(context.Background(), pipelineTimeout)
	defer cancel()

	r, err := harness.runPipeline(ctx, loadPCM(t, "address_gandalf"), "player-1")
	if err != nil {
		t.Fatalf("pipeline: %v", err)
	}

	t.Logf("Latency: VAD=%v STT=%v Total=%v Frames=%d",
		r.VADLatency, r.STTLatency, r.TotalLatency, r.OutputFrameCount)

	if r.VADLatency > 500*time.Millisecond {
		t.Errorf("VAD latency %v exceeds 500ms", r.VADLatency)
	}
	// Whisper base.en on CPU can take 5-20s depending on load. The 30s
	// threshold is generous for CI but ensures the pipeline completes.
	if r.TotalLatency > 30*time.Second {
		t.Errorf("total latency %v exceeds 30s", r.TotalLatency)
	}
	if r.RoutedTo != "gandalf" {
		t.Errorf("routed to %q, want gandalf", r.RoutedTo)
	}
}

// ─── Tests: VAD ─────────────────────────────────────────────────────────────

func TestVoiceE2E_VADSilenceDetection(t *testing.T) {
	t.Parallel()
	vadEng := energyvad.New(energyvad.WithMinSpeechFrames(3))
	sess, err := vadEng.NewSession(vad.Config{
		SampleRate: sttSampleRate, FrameSizeMs: vadFrameSizeMs,
		SpeechThreshold: 0.5, SilenceThreshold: 0.35,
	})
	if err != nil {
		t.Fatalf("create VAD: %v", err)
	}
	defer sess.Close()

	silence := makeSilentPCM(sttSampleRate, 1, 2000)
	frameSizeBytes := sttSampleRate * vadFrameSizeMs / 1000 * 2
	var speechStarted bool
	for off := 0; off+frameSizeBytes <= len(silence); off += frameSizeBytes {
		ev, err := sess.ProcessFrame(silence[off : off+frameSizeBytes])
		if err != nil {
			t.Fatalf("ProcessFrame: %v", err)
		}
		if ev.Type == vad.VADSpeechStart {
			speechStarted = true
		}
	}
	if speechStarted {
		t.Error("VAD detected speech in silence")
	}
}

func TestVoiceE2E_VADSpeechDetection(t *testing.T) {
	t.Parallel()
	vadEng := energyvad.New(energyvad.WithMinSpeechFrames(2))
	sess, err := vadEng.NewSession(vad.Config{
		SampleRate: sttSampleRate, FrameSizeMs: vadFrameSizeMs,
		SpeechThreshold: 0.5, SilenceThreshold: 0.35,
	})
	if err != nil {
		t.Fatalf("create VAD: %v", err)
	}
	defer sess.Close()

	pcm := loadPCM(t, "address_gandalf")
	frameSizeBytes := sttSampleRate * vadFrameSizeMs / 1000 * 2
	var started, ended bool
	for off := 0; off+frameSizeBytes <= len(pcm); off += frameSizeBytes {
		ev, err := sess.ProcessFrame(pcm[off : off+frameSizeBytes])
		if err != nil {
			t.Fatalf("ProcessFrame: %v", err)
		}
		if ev.Type == vad.VADSpeechStart {
			started = true
		}
		if ev.Type == vad.VADSpeechEnd {
			ended = true
		}
	}
	if !started {
		t.Error("VAD did not detect speech")
	}
	t.Logf("VAD: start=%v end=%v", started, ended)
}

// ─── Tests: Silero VAD (known ONNX 1.24 issue) ─────────────────────────────

func TestVoiceE2E_SileroVAD(t *testing.T) {
	t.Parallel()
	// Known: Silero VAD v5 model + ORT 1.24 → LSTM shape mismatch.
	sileroModel := filepath.Join("testdata", "silero_vad.onnx")
	if _, err := os.Stat(sileroModel); err != nil {
		t.Skipf("model not found: %v", err)
	}
	onnxLib := "/tmp/onnx-install/lib/libonnxruntime.so"
	if p := os.Getenv("ONNX_LIB_PATH"); p != "" {
		onnxLib = p
	}
	if _, err := os.Stat(onnxLib); err != nil {
		t.Skipf("ORT not found: %v", err)
	}

	vadEng, err := silerovad.New(sileroModel, silerovad.WithONNXLibPath(onnxLib))
	if err != nil {
		t.Skipf("silero init: %v", err)
	}
	sess, err := vadEng.NewSession(vad.Config{
		SampleRate: sttSampleRate, FrameSizeMs: 64,
		SpeechThreshold: 0.5, SilenceThreshold: 0.35,
	})
	if err != nil {
		t.Skipf("silero session: %v", err)
	}
	defer sess.Close()

	pcm := loadPCM(t, "address_gandalf")
	frame := pcm[:sttSampleRate*64/1000*2]
	_, err = sess.ProcessFrame(frame)
	if err != nil {
		t.Skipf("silero inference (known ORT 1.24 issue): %v", err)
	}
	t.Log("Silero VAD works — ORT compatibility resolved")
}
